services:
  api:
    build: .
    ports:
      - 8080:8080
    volumes:
      - ./config.yaml:/app/config.yaml
    environment:
      - MONGODB_URI=mongodb://mongo:27017

  mongo:
    image: mongo:7
    ports:
      - "27017:27017"
