name: Go Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker
        uses: docker/setup-docker@v1

      - name: Build and test
        run: |
          docker build -t lxdexplorer-api .
          docker run lxdexplorer-api go test ./...

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Tag and push to Docker Hub
        run: |
          docker tag lxdexplorer-api ${{ secrets.DOCKER_USERNAME }}/lxdexplorer-api:${{ github.sha }}
          docker push ${{ secrets.DOCKER_USERNAME }}/lxdexplorer-api:${{ github.sha }}
