name: Go Build and Deploy

on:
  push:
    branches:
      - main
    tags:
      - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.22

      - name: Get dependencies
        run: go get -v -t ./...

      - name: Build
        run: go build -v ./...

      - name: Run tests with coverage
        run: go test -race -coverprofile=coverage.txt -covermode=atomic ./...

  build:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ secrets.DOCKER_USERNAME }}/lxdexplorer-api
          tags: |
            type=edge
            type=semver,pattern={{version}}

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout Infra code
        uses: actions/checkout@v4
        with:
          repository: willie-cadete/homelab
          token: ${{ secrets.GH_PAT }}
          path: infra

      - name: Update Docker Image
        run: |
          TAG=$(echo ${{ github.ref }} | sed 's/refs\/tags\/v//')
          echo "image: williecadete/lxdexplorer-api:$TAG"
          sed -i "s|image: williecadete/lxdexplorer-api:.*|image: williecadete/lxdexplorer-api:$TAG|" infra/kubernetes/manifests/lxdexplorer-api/deployment.yml
          git add .
          git commit -m "Update lxdexplorer-api image to $TAG"
          git push
